SELECT * FROM customer_data LIMIT 20

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer_data
GROUP by gender

--Q2. Which customers used a discount but still spend more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer_data
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) from customer_data)

--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::NUMERIC),2) as "Average Product Rating"
from customer_data
group by item_purchased
order by avg(review_rating) DESC
LIMIT 5

--Q4. Compare the average amounts between Standard and Express Shipping.
SELECT shipping_type, round(avg(purchase_amount),2)
from customer_data
where shipping_type in ('Standard', 'Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, 
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as average_spend,
round(sum(purchase_amount),2) as total_revenue
FROM customer_data
group by subscription_status
order by average_spend, total_revenue desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied
SELECT item_purchased,
round(100 * sum(CASE WHEN discount_applied = 'Yes' THEN 1 else 0 end)/count(*),2) as discount_rate
from customer_data
group by item_purchased
order by discount_rate DESC
limit 5;

--Q7. Segment customers into new, returning and loyal based on their total number of previous purchases and show the count of each segment.
with customer_type as(
  SELECT customer_id, previous_purchases,
  case
  when previous_purchases = 1 THEN 'New'
  when previous_purchases BETWEEN 2 and 5 then 'Returning'
  else 'Loyal' end as customer_segment
  from customer_data
)
SELECT customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
with item_count as(
  SELECT item_purchased, category,
  count(customer_id) as total_orders,
  ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
  from customer_data
  group by item_purchased, category
)
SELECT item_rank, category, item_purchased, total_orders
from item_count
WHERE item_rank <=3

--Q9. Are customers who are repeat buyers(more than 5 previous purchases) likely to subscribe?

SELECt subscription_status,
count(customer_id) as repeat_buyers
from customer_data
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
  
SELECT age_group, sum(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue DESC